name: Publish Simple-ui-vite To Npm

on:
  push:
    branches: [publish-simple-ui-vite]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0

      #安装依赖
      - name: Install modules
        run: pnpm install

      # 打包
      - name: Build
        run: npm run build

      # 推送到 NPM 上
      - name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish
          env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
